version: '3'
services:
  db:
    image: mysql:8.0.23
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASES=db-api
